### ISSUE TITLE
bump up version to 0.0.6?

### ISSUE THREAD

**Issue by kpx-dev** [grauwoelfchen/flask-dotenv#10]
Hi,

I needed the comment feature in the .env, can you bump up version and push to pip?

Thanks.

**Comment by grauwoelfchen** [comment]
Oh, I've forgotten about it. Thank you for request :)

Please wait just a moment.
I will merge pull request #9 then push new version to pip at once.

**Comment by grauwoelfchen** [comment]
@kienpham2000 

I've just released 0.0.6 now.
Please let me know if you have something problem ;)
- [Flask-DotEnv on testpypi](https://testpypi.python.org/pypi/Flask-DotEnv/0.0.6)
- [Flask-DotEnv on pypi](https://pypi.python.org/pypi/Flask-DotEnv/0.0.6)
