### ISSUE TITLE
Support appropriate type conversions

### ISSUE THREAD

**Issue by nihonjinrxs** [grauwoelfchen/flask-dotenv#5]
It would be really nice to be able to support appropriate type conversions to standard Python types.

For example, [this BitBucket project](https://bitbucket.org/romabysen/flask-envconfig/src/322b4817d2fb1a3b71b8ffe818ab8d45968a5830/flask_envconfig.py?at=default&fileviewer=file-view-default) doesn't support `DotEnv`, only OS Environment variables, but does appropriate type conversions via the `ast` module.  The relevant code looks something like this:

``` python
from __future__ import absolute_import
import ast
from os import environ

class EnvConfig(object):
    def __init__(self, app): ...
    def init_app(self, app):
        for key, value in environ.iteritems():
            try:
                value = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                pass
            app.config[key] = value
```

Is this something you're willing to add to this project?  I'm happy to implement and submit a PR.

**Comment by grauwoelfchen** [comment]
Thanks for your suggestion.

I've tried your snipet that enables to wirte python abstract syntax grammer in .env file.
This is really nice ;)

And then, I've written a small test case to confirm it:

``` python
# FEATURES="{'DotEnv': True}" in .env
def test_loaded_value_is_evaluated_as_abstract_syntax_grammer(self):
      self.env.init_app(self.app)
      self.assertEqual({'DotEnv': True}, self.app.config['FEATURES'])
```

I think this feature (type conversion) is very helpfull for us.
Let's tolerate its overhead (cost) by `try ... except` block for normal value.

Could you please send me PR?
It's very welcome.

**Comment by grauwoelfchen** [comment]
@nihonjinrxs  May I implement this by myself? or would you like to add?

**Comment by nihonjinrxs** [comment]
@grauwoelfchen Sorry, work got really busy and I didn't have time to get back to this.  I'll implement and submit a PR shortly.

**Comment by grauwoelfchen** [comment]
Thank you for thoroughly pull request. (ChangeLog too!)
It's very nice :+1: 

But I found some small concerns:

### verbose_mode

It seems that `verbose_mode` does not work for [this change](https://github.com/nihonjinrxs/flask-dotenv/commit/1b2da733d6810e72ce2dd7b15f5f70d96be7d986#diff-3b303c734a8f7d849fd01f38f4bd720aL25). It needs to be assigned to enable verbose mode by optional argument at here.

``` py
def init_app(self, app, env_file=None, verbose_mode=False):                 
    if self.app is None:                                                    
        self.app = app 
    self.verbose_mode = verbose_mode # => this line
```

### log messages

And [this line](https://github.com/nihonjinrxs/flask-dotenv/commit/1b2da733d6810e72ce2dd7b15f5f70d96be7d986#diff-3b303c734a8f7d849fd01f38f4bd720aR44) will output many messages like this:

``` sh
# I've got these outputs with `verbose_mode` on sample project.
% python manage.py runserver
 * SECRET_KEY: value ":)" of type <class 'str'> cast to <class 'str'>
 * Overwriting an existing config var: SECRET_KEY
 * MAIL_SERVER: value "smtp.example.org" of type <class 'str'> cast to <class 'str'>
 * Overwriting an existing config var: MAIL_SERVER
 * MAIL_PORT: value 587 of type <class 'str'> cast to <class 'int'>
 * Overwriting an existing config var: MAIL_PORT
 * MAIL_USERNAME: value "foo.bar@example.org" of type <class 'str'> cast to <class 'str'>
 * Overwriting an existing config var: MAIL_USERNAME
 * MAIL_PASSWORD: value "foo.bar.baz" of type <class 'str'> cast to <class 'str'>
 * Overwriting an existing config var: MAIL_PASSWORD
 * MAIL_SENDER: value "Foo <foo.bar@example.org>" of type <class 'str'> cast to <class 'str'>
 * Overwriting an existing config var: MAIL_SENDER
 * DATABASE_URL: value "" of type <class 'str'> cast to <class 'str'>
 * Setting an entirely new config var: DATABASE_URL
 * DEVELOPMENT_DATABASE_URL: value "postgresql://qux:quux@localhost/baz_development" of type <class 'str'> cast to <class 'str'>
 * Setting an entirely new config var: DEVELOPMENT_DATABASE_URL
 * TEST_DATABASE_URL: value "postgresql://qux:quux@localhost/baz_test" of type <class 'str'> cast to <class 'str'>
 * Setting an entirely new config var: TEST_DATABASE_URL
 * Mapping a specified var as a alias: SQLALCHEMY_DATABASE_URI => DEVELOPMENT_DATABASE_URL
```

It really makes sense and messages are very friendly. But I think that these outputs may be a little noisy.

So, after merge your PR, I will add small changes to fix these issues for above reasons :wink: 
# ...and at next time, you could submit a PR from [topic branch](https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request) (not master), then I will be more happy ;)

Anyway, Thank you so much!
